apiVersion: v1
kind: Service
metadata:
  name: eco-bot
  namespace: default
  labels:
    app: eco-bot
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: eco-bot
  type: ClusterIP
