apiVersion: apps/v1
kind: Deployment
metadata:
  name: eco-backend
  namespace: default
  labels:
    app: eco-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eco-backend
  template:
    metadata:
      labels:
        app: eco-backend
    spec:
      containers:
        - name: eco-backend
          image: romanmartyny/backend:5568b6c70ded15dece6180e278c3457d24c3eed3
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://postgres:postgres@postgres:5432/eco_db"
            - name: HOST
              value: "postgres"
            - name: PORT
              value: "5432"
          resources:
            requests:
              memory: "256Mi"
              cpu: "128m"
            limits:
              memory: "512Mi"
              cpu: "256m"
