apiVersion: v1
kind: Service
metadata:
  name: eco-backend
  namespace: default
  labels:
    app: eco-backend
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: eco-backend
  type: ClusterIP
